[build]
  command = "cd frontend && npm install && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 