[build]
  command = "cd frontend && npm install && npm install glob && node fix-scss-imports.js && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 