[build]
  command = "cd frontend && node netlify-build.js"
  publish = "frontend/dist/frontend/browser"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 