[build]
  command = "cd frontend && npm install && npx ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[build.environment]
  NODE_VERSION = "18.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 